### ISSUE TITLE
TypeError: container.setAttribute is not a function   

### ISSUE THREAD

**Issue by jeromevillaver** [nuxy/vue-slot-machine-gen#1]
Error

```
slot-machine.js:62  Uncaught (in promise) TypeError: container.setAttribute is not a function
    at initGame (slot-machine.js:62:15)
    at slot-machine.js:52:7
    at new SlotMachine (slot-machine.js:56:3)
```

This is how display the <SlotMachine>

```
<div class="slot-machine-container">
  <slot-machine
    v-bind:reels="reels"
    v-bind:options="options"
    v-bind:callback="callback"
    v-bind:play="start"
  />
</div>
```

This is the whole component

```

<script setup>
import { ref, computed, nextTick, onMounted } from "vue";
import AdminLayout from "@/Layouts/Admin.vue";
import background from "../../../assets/img/slot-bg.jpeg";
import startImage from "../../../assets/img/start.png";
import SlotMachine from "vue-slot-machine-gen";
import { Fireworks } from "fireworks-js";

const betAmount = ref(null);
const start = ref(false);
const disableReset = ref(true);
const noBetAmount = ref(false);
const winnerText = ref(false);
const loserText = ref(false);
const fireworks = ref(false);

const startGame = () => {
  if (validBetAmount.value) {
    console.log("click");
    noBetAmount.value = false;
    start.value = true;
    disableReset.value = false;
  } else {
    noBetAmount.value = !validBetAmount.value;
  }
};

const imageUrl = "https://nuxy.github.io/slot-machine-gen/images";
const soundUrl = "https://nuxy.github.io/slot-machine-gen/sounds";

const options = {
  sounds: {
    reelsBegin: `${soundUrl}/reelsBegin.mp3`,
    reelsEnd: `${soundUrl}/reelsEnd.mp3`,
  },
};

const reels = [
  {
    imageSrc: `${imageUrl}/reel-strip1.png`,
    symbols: [
      {
        title: "cherry",
        position: 100,
        weight: 2,
      },
      {
        title: "plum",
        position: 300,
        weight: 6,
      },
      {
        title: "orange",
        position: 500,
        weight: 5,
      },
      {
        title: "bell",
        position: 700,
        weight: 1,
      },
      {
        title: "cherry",
        position: 900,
        weight: 3,
      },
      {
        title: "plum",
        position: 1100,
        weight: 5,
      },
    ],
  },
  {
    imageSrc: `${imageUrl}/reel-strip2.png`,
    symbols: [
      {
        title: "orange",
        position: 100,
        weight: 6,
      },
      {
        title: "plum",
        position: 300,
        weight: 5,
      },
      {
        title: "orange",
        position: 500,
        weight: 3,
      },
      {
        title: "plum",
        position: 700,
        weight: 5,
      },
      {
        title: "cherry",
        position: 900,
        weight: 2,
      },
      {
        title: "bell",
        position: 1100,
        weight: 1,
      },
    ],
  },
  {
    imageSrc: `${imageUrl}/reel-strip3.png`,
    symbols: [
      {
        title: "cherry",
        position: 100,
        weight: 4,
      },
      {
        title: "bell",
        position: 300,
        weight: 1,
      },
      {
        title: "orange",
        position: 500,
        weight: 6,
      },
      {
        title: "plum",
        position: 700,
        weight: 5,
      },
      {
        title: "plum",
        position: 900,
        weight: 3,
      },
      {
        title: "cherry",
        position: 1100,
        weight: 2,
      },
    ],
  },
];

const callback = function (payLine) {
  console.log(payLine[0].title + " | " + payLine[1].title + " | " + payLine[2].title);

  if (payLine[0].title === payLine[1].title && payLine[0].title === payLine[2].title) {
    new Audio(`${soundUrl}/winner.mp3`).play();
  }
};

const resetButton = () => {
  console.log("click");
  disableReset.value = true;
  betAmount.value = null;
  winnerText.value = false;
  loserText.value = false;
};

const validBetAmount = computed(() => {
  return betAmount.value !== null && betAmount.value > 0;
});

const containerFireworks = ref(null);
const fireworksEffect = ref(null);

onMounted(() => {
  containerFireworks.value = document.querySelector(".containerFireworks");

  if (containerFireworks.value) {
    fireworksEffect.value = new Fireworks(containerFireworks.value, {});
    fireworksEffect.value.start();
  }

  const container = document.querySelector(".slot-machine-container");
  if (container) {
    container.setAttribute("aria-label", "Slot machine");
    slotEffect.value = new SlotMachine(container, {
      // Add any options you need for SlotMachine initialization
    });
  }
});
</script>
<template>
  <AdminLayout>
    <div class="flex flex-wrap">
      <div class="w-full lg:w-12/12 px-4">
        <div
          class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0"
        >
          <div class="rounded-t bg-white mb-0 px-6 py-6">
            <div class="text-center flex justify-between">
              <h6 class="text-blueGray-700 text-xl font-bold">Lucky Seven Game</h6>
              <button
                type="button"
                :disabled="disableReset"
                @click="resetButton"
                class="bg-emerald-500 text-white active:bg-emerald-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 ease-linear transition-all duration-150"
              >
                Reset
              </button>
            </div>
          </div>
          <div
            class="flex-auto px-4 lg:px-10 py-10 pt-0 w-full bg-cover"
            :style="{ 'background-image': 'url(' + background + ')' }"
            :class="{ 'h-64 md:h-auto': !background }"
          >
            <div
              v-show="noBetAmount"
              class="bg-amber-100 border-t-4 border-amber-500 rounded-b text-amber-900 px-4 py-3 mt-2 shadow-md"
              role="alert"
            >
              <div class="flex">
                <div class="py-1">
                  <svg
                    class="fill-current h-6 w-6 text-amber-500 mr-4"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                  >
                    <path
                      d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"
                    />
                  </svg>
                </div>
                <div>
                  <p class="font-bold">No Bet Amount</p>
                  <p class="text-sm">Make Sure you place bet amount to start the game</p>
                </div>
              </div>
            </div>
            <div class="relative rounded-md mt-5 text-center">
              <div class="absolute inset-0 bg-cyan-900 opacity-65 rounded-md"></div>
              <div
                v-show="fireworks"
                class="containerFireworks absolute inset-0 z-30"
              ></div>
              <div class="absolute inset-7 z-20 pointer-events-none">
                <h1
                  v-show="winnerText"
                  class="blink-zoom text-green-400 text-7xl md:text-4xl sm:text-3xl"
                >
                  You Win!
                </h1>
                <h1
                  v-show="loserText"
                  class="blink-zoom text-red-400 text-7xl md:text-4xl sm:text-3xl"
                >
                  You Lose!
                </h1>
              </div>
              <div class="relative z-10">
                <div v-show="start" class="grid grid-cols-5 gap-4 text-center p-5">
                  <!-- <div class="container">
                        <h1>Test</h1>
                        <SlotMachine :options="options" :indexes="indexes" :reels="reels" />
                    </div> -->
                  <div class="slot-machine-container">
                    <slot-machine
                      v-bind:reels="reels"
                      v-bind:options="options"
                      v-bind:callback="callback"
                      v-bind:play="start"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div class="flex flex-col md:flex-row mt-5">
              <div
                class="bg-teal-800 p-2 rounded-lg opacity-50 mb-2 md:mb-0 md:mr-2 w-full md:w-auto md:flex-1"
              >
                <div class="relative bg-inherit">
                  <input
                    type="number"
                    v-model="betAmount"
                    class="peer bg-transparent h-10 w-full rounded-lg text-white placeholder-transparent ring-2 px-2 ring-white focus:slate-200 focus:outline-none focus:border-slate-200"
                    placeholder="Place Bet"
                    min="0"
                    required
                  />
                  <label
                    class="absolute cursor-text left-0 -top-3 text-sm text-gray-500 bg-inherit mx-1 px-1 peer-placeholder-shown:text-base peer-placeholder-shown:text-white peer-placeholder-shown:top-2 peer-focus:-top-3 peer-focus:text-white peer-focus:text-sm transition-all"
                    >Place Bet</label
                  >
                </div>
              </div>
              <div
                class="flex justify-center md:justify-end items-center w-full md:w-auto"
              >
                <button
                  class="rounded-full shadow outline-none focus:outline-none w-16 h-16 md:w-12 md:h-12 aspect-w-1 aspect-h-1 pushable"
                  type="button"
                  @click="startGame"
                >
                  <img :src="startImage" alt="Image" class="w-full h-full object-cover" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </AdminLayout>
</template>
<style scoped>
.pushable {
  transition: transform 0.2s;
}

.pushable:hover {
  transform: scale(0.95);
}

.pushable:active {
  transform: scale(0.9);
}

/*text message */
@keyframes blink {
  0% {
    opacity: 1;
  }
  50% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@keyframes zoom {
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.2);
  }
  100% {
    transform: scale(1);
  }
}

.blink-zoom {
  animation: blink 1s infinite, zoom 3s infinite;
}
</style>

```

**Comment by nuxy** [comment]
Hi @jeromevillaver

Based on the provided example the issue seems to be with the following code:

```
const container = document.querySelector(".slot-machine-container");
if (container) {
  container.setAttribute("aria-label", "Slot machine"); 
  slotEffect.value = new SlotMachine(container, {
    // Add any options you need for SlotMachine initialization
  });
}
```

It looks like you're using the [standard library (non-Vue) implementation](https://github.com/nuxy/slot-machine-gen).  If that was not intended, I have provided a working example of the [Vue component integration](https://github.com/nuxy/vue-slot-machine-gen/blob/master/demo/index.js).

**Comment by nuxy** [comment]
If you have any further questions, let me know.  Until then I'm closing this issue.
